apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kubernetes-frontend
  namespace: demo-kubernetes-dev
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-kubernetes-frontend
  template:
    metadata:
      labels:
        app: demo-kubernetes-frontend
        version: v1
    spec:
      containers:
      - name: demo-kubernetes-frontend
        image: torrient/demo-kubernetes-frontend:dev_v11