apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kubernetes-frontend
  namespace: demo-kubernetes-prod
  labels:
    app: demo-kubernetes-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-kubernetes-frontend
  template:
    metadata:
      labels:
        app: demo-kubernetes-frontend
    spec:
      containers:
      - name: demo-kubernetes-frontend
        image: torrient/demo-kubernetes-frontend:prod_v1