apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: deployment.yaml
  target:
    kind: Deployment
namespace: demo-kubernetes-prod
resources:
- ./namespace.yaml
- ../../base
