apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-kubernetes-frontend
  labels:
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-kubernetes-frontend
  template:
    metadata:
      labels:
        app: demo-kubernetes-frontend
        version: v1
    spec:
      containers:
      - name: demo-kubernetes-frontend
        image: torrient/demo-kubernetes-frontend:v1
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        imagePullPolicy: Always
        ports:
        - containerPort: 8501
        env:
          - name: HOST_SERVICE
            value: "demo-kubernetes-backend-service"